### ISSUE TITLE
Update permitted `<title>` field format

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/pphtml#14]
PG are updating their preferred `<title>` format to
`<title>Alice's Adventures in Wonderland | Project Gutenberg</title>`

pphtml's title check/message will need updating too.

**Comment by rtonsing** [comment]
It seems to be fine with it already - no warning or error, just a normal info either way:

> [info] title/h1 compare:
>        title: The Murder of Roger Ackroyd, by Agatha Christie | Project Gutenberg
>           h1: THE MURDER OF  ROGER ACKROYD

Have you seen an issue?

**Comment by windymilla** [comment]
Fixed by #15
