### ISSUE TITLE
pphtml should not treat "CSS used but not defined" as a "FAIL"

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/pphtml#4]
It is not an error if a class name is used on an element, but that class is not used as a selector in the CSS.
It may be a mistake, e.g. a typo, so I think it is correct to "warn" about it, but it should not be a "FAIL"

I think the relevant line of code is [this one](https://github.com/DistributedProofreaders/pphtml/blob/4aad63f27771c6273a0dccec3c39219724dd0514/pphtml.py#L1157) where the word "FAIL" should be changed to "warn"

**Comment by asylumcs** [comment]
I agree. "FAIL" should more closely reflect what the CSS validator would flag. As long as it is still a "warn" it makes sense.

**Comment by cpeel** [comment]
This was resolved in https://github.com/DistributedProofreaders/pphtml/pull/6
