### ISSUE TITLE
Consider treating the special ebookmaker classes differently regarding CSS warnings 

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/pphtml#5]
The classes x-ebookmaker and x-ebookmaker-drop are added/used by ebookmaker, but they currently may generate "used but not defined" warnings/errors (see #4 ) from pphtml

There is an argument for assuming these two classes will be handled by ebookmaker so the user does not need to be alarmed by "used but not defined" or "defined but not used" warnings about them, which could also obscure genuine warnings.

**Comment by asylumcs** [comment]
Is it best practice to include ".x-ebookmaker {}" in the CSS to both avoid the warning and to signal that leaving it empty (until it is cascaded by ebookmaker) is intentional? Are you suggesting that these two class names be hardcoded exceptions? And I wonder about our fadedpage.com PPers who use these tools but don't use ebookmaker. Not sure what your action item for this would be.

**Comment by windymilla** [comment]
Sorry - I wasn't sure what the action would be either, hence my weasel words "Consider..." and "There is an argument..."

I think my personal view is that hardcoded exceptions are a bad idea, and for my own use I certainly would happily ignore the "warn" if it were changed to that. Tools such as pphtml and many others that we use, give us warnings to say "check this - is it what you wanted?", which I'm very happy with.

I've no idea if ".x-ebookmaker {}" would be a good thing or not. Someone who didn't know about ebookmaker wouldn't really be any wiser reading the code. If they saw the HTML version, they wouldn't see any HTML elements with the x-ebookmaker class, so might wonder why that empty CSS line was there and why other CSS selectors used x-ebookmaker. If they saw the epub version, they would see the x-ebookmaker class on the body element and could see the purpose of the other selectors, with or without that empty declaration. I have used (or at least considered) the equivalent situation with tables, e.g. if you have several tables where you want all the td's to be centered, you can just give those tables a classname and then use
table.classname td {...}
There is no need for a 
.classname {...} if you don't need to style the table itself.

In the [forum where this was brought up](https://www.pgdp.net/phpBB3/viewtopic.php?f=3&t=15019&start=21975#p1232166), I wrote "I'm not sure whether that is a good idea or not - it would need thought from people who understand the situation well." Hence this issue and my gratitude at your input.

Particularly since the tools are used by non-DP producers, I would be fine with ignoring this issue, and closing it unless others come up with strong arguments for making a change. If issue #4 were done, then hopefully the PPers who are concerned by the error would be less concerned by it just being a warning.

**Comment by asylumcs** [comment]
I would close this and implement #4 as you suggested.

**Comment by cpeel** [comment]
Closing as issue #4 was resolved in pull request https://github.com/DistributedProofreaders/pphtml/pull/6. Please re-open if this is incorrect.
